Relic:
  set_to_names:
    战狂:
    - K1
    - K2
    - K3
    - K4
    流浪大地:
    - K1
    - K2
    - K3
    - K4
    角斗士:
    - K1
    - K2
    - K3
    - K4
  valid_items:
  - 攻击力
  - 攻击力%
  - 生命值
  - 生命值%
  - 暴击率%
  - 暴击伤害%
  - 元素精通
  valid_locations:
  - 头部
  - 身体
  - 脚
  valid_sets:
  - 战狂
  - 角斗士
  - 流浪大地
